services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./meta/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=forum